### ISSUE TITLE
bug: в модалке на телефоне, скролл не работает

### ISSUE THREAD

**Issue by VitiaCatDragon** [ZationRU/ReactUI#11]
Есть создать внутри модалки контейнер, который будет иметь скролл (скорее всего из-за state-layer
![изображение](https://github.com/ZationRU/ReactUI/assets/60291267/348c73a3-50b1-4e26-92b1-52d6b80f979d)

**Comment by levkopo** [comment]
Fixed in 1.1.0-dev16
